#' Generates a plot of the type of task by date of task
#' @param longdate_tasks A dataset of tasks by date in long form, should be generated by mcex_longtasks() of tasks a student should perform. Should be generated by mcex_weekn(). Default is 24
#' @param date_breaks A string which describes the scale of the x axis, default is one-week
#' @returns A plot describing number of tasks by date
#' @examples
#' mcexplot_datetasks(longdate_tasks)



mcexplot_datetasks <- function(longdate_tasks, date_breaks = "1 week"){

  db <- date_breaks

longdate_tasks %>%
  ggplot(aes(x=DateOfTask, y=count, fill = Task)) +
  geom_bar(stat = "identity") +
  scale_x_date(date_breaks = {{db}}) +
  theme(axis.text.x = element_text(angle = 90), legend.position = 'bottom')

}
