#' Generates a dataframe of the dates of tasks that have been performed. Generally a helper function for mcex_longdatetasks
#' @param minicex_data A cleaned MiniCEx dataset, should be generated by mcex_read()
#' @returns A dataframe containing dates of tasks and count of task type
#' @examples
#' dateTasks <- mcex_datetasks(minicex_data)





mcex_datetasks <- function(minicex_data) {

  minicex_data %>%
    group_by(DateOfTask) %>%
    summarise(ClinicalExam = sum(ClinicalExam),
              Diagnostics = sum(Diagnostics),
              MedTx = sum(MedTx),
              SurgTx = sum(SurgTx),
              CommsSkills = sum(CommsSkills),
              Dentistry = sum(Dentistry),
              totalTasks = sum(taskCounter))

}
