#' Generates a generic plot with facets utilised in analysis where the number of tasks can be viewed via specified vars
#' @param minicex_data A cleaned MiniCEx dataset, should be generated by mcex_read()
#' @param x_var The variable for the x axis, can be either matric or week. Default is week
#' @param fill_var A factor from the dataset to fill the data. Usually Spp or OverallAssessorFeedback. Default is OverallAssessorFeedback
#' @param facet_var A factor from the dataset to use as a facet. Default is Spp
#' @returns A plot describing number of tasks by chosen vars with a faceting variable
#' @examples
#' mcexplotfacet_tasks(minicex_data, x_var = matric, fill_var = OverallAssessorFeedback, facet_var = Spp)





mcexplot_facettasks <- function(minicex_data, x_var = week, fill_var = OverallAssessorFeedback, facet_var = Spp){

  x_var = enquo(x_var)

  fill_var = enquo(fill_var)

  facet_var = enquo(facet_var)

  ddd <- minicex_data %>%
    mutate(week = week(DateOfTask))

  ddd %>%
    ggplot(aes(x={{x_var}}, y=taskCounter, fill = {{fill_var}})) +
    geom_bar(stat = "identity") +
    theme(axis.text.x = element_text(angle = 90), legend.position = 'bottom') +
    facet_wrap(facets = vars({{facet_var}})) +
    labs(title = "Performance by week of task and species")

}
