#' Generates a plot of the number of tasks per student/week
#' @param minicex_data A cleaned MiniCEx dataset, should be generated by mcex_read()
#' @param x_var The variable for the x axis, can be either matric or week. Default is matric
#' @param fill_var A factor from the dataset to fill the data.Can be Spp or OverallAssessorFeedback
#' @returns A plot describing number of tasks by student
#' @examples
#' mcexplot_tasks(longdate_tasks)



mcexplot_tasks <- function(minicex_data, x_var = c(matric, week), fill_var = c(Spp, OverallAssessorFeedback)){

  x_var = enquo(x_var)

  fill_var = enquo(fill_var)

  ddd <- minicex_data %>%
    mutate(week = week(DateOfTask))

  ddd %>%
    ggplot(aes(x=!!x_var, y=taskCounter, fill = {{fill_var}})) +
    geom_bar(stat = "identity") +
    theme(axis.text.x = element_text(angle = 90), legend.position = 'bottom')


}



