#' Generates a plot of the type of task by date of task
#' @param minicex_data A cleaned MiniCEx dataset, should be generated by minicex_read()
#' @param date_breaks A string which describes the scale of the x axis, default is one-week
#' @returns A plot describing number of tasks by date
#' @examples
#' mcexplot_datetasks(longdate_tasks)



mcexplot_datetasks <- function(minicex_data, date_breaks = "1 week"){

  db <- date_breaks

  minicex_data %>%
  mcex_longdatetasks() %>%
  ggplot(aes(x=DateOfTask, y=count, fill = Task)) +
  geom_bar(stat = "identity") +
  scale_x_date(date_breaks = {{db}}) +
  theme(axis.text.x = element_text(angle = 90), legend.position = 'bottom')

}
