#' Generates a long dataframe of the dates of tasks that have been performed
#' @param minicex_data A cleaned MiniCEx dataset, should be generated by mcex_read()
#' @returns A dataframe containing dates of tasks and count of task type
#' @examples
#' dateTasksLong <- mcex_longdatetasks(minicex_data)



mcex_longdatetasks <- function(minicex_data){

  minicex_data %>%
    mcex_datetasks() %>%
    pivot_longer(cols = -c(DateOfTask, totalTasks), names_to = "Task", values_to = "count")

}
