#' Generates a dataframe of students who have not performed enough tasks
#' @param week_requirement A numeric representation of the number of tasks a student should perform. Should be generated by mcex_weekn(). Default is 24
#' @param minicex_data A cleaned MiniCEx dataset, should be generated by mcex_read()
#' @returns A dataframe containing the number of students who have not performed enough tasks
#' @examples
#' notEnoughTasks <- mcex_enoughtasks(minicex_data, week_requirement)





mcex_enoughtasks <- function(minicex_data, week_requirement = 24){

  minicex_data <- minicex_data

  namesMatric <- minicex_data %>%
    select(matric, StudentName)


  notEnoughTasks <- mcex_tasks(minicex_data) %>%
    filter(totalTasks < week_requirement) %>%
    select(matric, totalTasks) %>%
    arrange("totalTasks") %>%
    left_join(namesMatric, by="matric") %>%
    mutate(totalTasks = as.numeric(totalTasks)) %>%
    unique() %>%
    group_by(matric, totalTasks) %>%
    nest(StudentName) %>%
    arrange(totalTasks) %>%
    unnest_wider(data, names_sep = "_")

  return(notEnoughTasks)
}






